
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fyrox-test = { path = "../game", default-features = false }

[features]
default = ["fyrox-test/default"]
dylib-engine = ["fyrox-test/dylib-engine"]
